#' EcoSamp CRS transformation function
#'
#' This function is a sub-function of ecosamp() function, which doesn't work on its own.
#' It loads the input target map, CRS, resolution and reference map (if provided),
#' generated/specified in the main function.
#' The function then transforms the CRS of the target map, and converts it based on its class:
#' 1. RasterLayer object: transforms map CRS into sd_crs, crop it to the same area as habitat map, if not the same.
#' 2. SF object: converts map into a SpatVector object and transforms map CRS into sd_crs
#'    (this is for calculating distance to roads/waters).
#' 3. SpatRaster object: crop map to the same area as habitat map, if not the same, 
#'    and transforms map CRS into sd_crs.
#' 
#' The function then outputs the transformed version of map.
#' 
#' @param map RasterLayer, SpatRaster or SF object, map produced/specified in the ecosamp() function,
#' which needs to be transformed in CRS and/or object class.
#' @param sd_crs String, the target UTM CRS code produced/specified in the ecosamp() function.
#' generated by prior runs in the sample generation loop of the ecosamp() function.
#' @param map_res Numeric, the resolution (in metres) of output maps, specified in the ecosamp() function,
#' 5(m) by default
#' @param ref_map RasterLayer, a map derived from map_habitat produced/specified in the ecosamp() function,
#' for cropping map_slope to the same area as map_habitat.
#' 
#' @return A transformed version of target map, in RasterLayer or SpatVector class.
#' @export
ecosamp_transcrs <- function(map, sd_crs, map_res = 5, ref_map = NULL){
  map_transformed <- NA
  if (is(map, "RasterLayer")) {
    # If map is a RasterLayer, convert it to corresponding resolution and CRS
    map_transformed <- raster::projectRaster(map,crs = sd_crs,res = map_res,method = "ngb")
    # When input is the slope map, it will be cropped to the same area as the habitat map
    if (!is.null(ref_map)){
      map_transformed <- raster::crop(map,extent(ref_map))
    }
  } else if (is(map, "sf")) {
    # If map is a SF object, convert it into a vector and then to corresponding CRS
    map <- terra::vect(map)
    map_transformed <- terra::project(map, sd_crs)
  } else if (is(map, "SpatRaster")) {
    # If map is a SpatRaster object (for slope map), crop and convert it to corresponding CRS
    ref_map <- raster::projectRaster(ref_map,crs = crs(map),method = "ngb")
    map_crop <- raster::crop(map,extent(ref_map))
    map_crop <- terra::project(map_crop, sd_crs,res=map_res)
    # Convert into RasterLayer object
    map_transformed <- raster::raster(map_crop)
  }
  return(map_transformed)
}