#' EcoSamp maximum distance sampling function
#'
#' This function is a sub-function of ecosamp() function, which doesn't work on its own.
#' It loads the valid region for generating sample points produced by the main function,
#' and existing sample points generated by previous sample generating loops.
#' 
#' Using the inputs, its caclculates the distance from all valid pixels to the existing points,
#' and select the valid pixel which is furthest away from all the existing points.
#' It then outputs the x and y coordinates of the selected pixel.
#' 
#' @param sites_sample RasterLayer, a binary map produced by the ecosamp() function,
#' with 1 indicating valid sample region and NA indicating invalid region.
#' @param sd_points Data frame, a dataframe containing x and y coordinates of existing points,
#' generated by prior runs in the sample generation loop of the ecosamp() function.
#' 
#' @return A data frame containing the x and y coordinates of the selected pixel.
#' @export
ecosamp_maxdist_select <- function(sites_sample, sd_points) {
  # Get cells that are still eligible
  sites_sample_cells <- which(!is.na(raster::values(sites_sample)))
  # Get coordinates of eligible cells
  sites_sample_xy <- raster::xyFromCell(sites_sample,sites_sample_cells)
  
  # If there are no existing sample points,
  # randomly select the first point
  if (nrow(sd_points) == 0) {
    furthest_cell <- sample(sites_sample_cells, size = 1)
  } else {
    # Coordinates of existing sample points
    existing_xy <- as.matrix(sd_points[, c("x", "y")])
    # For every eligible cell, calculate distance to the nearest existing sample point
    min_dist <- apply(
      sapply(seq_len(nrow(existing_xy)),
             function(i) {
               sqrt((sites_sample_xy[, 1] - existing_xy[i, 1])^2 +
                      (sites_sample_xy[, 2] - existing_xy[i, 2])^2)
             }),
      1, min)
    
    # Select the eligible cell with the furthest distance to its nearest existing sample point
    furthest_cell <- sites_sample_cells[which.max(min_dist)]
  }
  
  # Convert selected cell to coordinates
  xy <- raster::xyFromCell(sites_sample,furthest_cell)
  
  # Return in the same basic format as sampleRandom(..., xy = TRUE)
  return(data.frame(x = xy[1],y = xy[2]))
}